import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faBars,
  faXmark,
  faScissors,
  faPalette,
  faSpa,
  faPhone,
  faLocationDot,
  faClock,
  faStar,
  faStarHalfStroke,
  faQuoteLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faEnvelope,
  faWandMagicSparkles,
  faHeart,
  faGem,
  faLeaf,
  faChevronLeft,
  faChevronRight,
  faDroplet,
  faCircleCheck,
  faHandSparkles,
  faHotTubPerson,
  faPlay,
  faBottleDroplet,
  faSprayCanSparkles,
} from '@fortawesome/free-solid-svg-icons'
import { faInstagram, faWhatsapp } from '@fortawesome/free-brands-svg-icons'

/**
 * Registra tutte le icone usate nel sito nella library di Font Awesome,
 * così da poterle referenziare per nome nei template.
 */
export function registerIcons(): void {
  library.add(
    faBars,
    faXmark,
    faScissors,
    faPalette,
    faSpa,
    faPhone,
    faLocationDot,
    faClock,
    faStar,
    faStarHalfStroke,
    faQuoteLeft,
    faArrowRight,
    faArrowUpRightFromSquare,
    faEnvelope,
    faWandMagicSparkles,
    faHeart,
    faGem,
    faLeaf,
    faChevronLeft,
    faChevronRight,
    faDroplet,
    faCircleCheck,
    faHandSparkles,
    faHotTubPerson,
    faPlay,
    faBottleDroplet,
    faSprayCanSparkles,
    faInstagram,
    faWhatsapp,
  )
}
